backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/oddfellows-hall.md"
        label: "Oddfellows Hall"
        name: "oddfellows-hall"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/discography.md"
        label: "Discography"
        name: "discography"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: 'Album Listing'
            name: 'album-listing'
            widget: 'list'
            fields:
              - label: 'Album'
                name: 'album'
                widget: 'object'
                fields:
                  - { label: 'CD Title', name: 'cd-title', widget: 'string' }
                  - { label: 'Year', name: 'year', widget: 'string', hint: 'Year' }
                  - { label: 'Artwork', name: 'artwork', widget: 'image' }
                  - { label: 'Details & Track Listing', name: "details-track-listing", widget: markdown }