backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "gigs"
    label: "Gigs"
    folder: "src/gigs"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gig-listing"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/oddfellows-hall.md"
        label: "Oddfellows Hall"
        name: "oddfellows-hall"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/gigs.md"
        label: "Gigs"
        name: "gigs"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: 'Gig Listing'
            name: 'gig-listing'
            widget: 'list'
            fields:
              - { label: 'Date', name: 'date', widget: 'date', format: 'dddd Do MMM YYYY' }
              - { label: 'Time', name: 'time', widget: 'string' }
              - { label: 'Location', name: 'location', widget: 'string' }
              - { label: 'Details', name: "details", widget: 'markdown' }
      - file: "src/pages/guestbook.md"
        label: "Guestbook"
        name: "guestbook"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/gallery.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Gallery", name: "gallery", widget: "image"}
      - file: "src/pages/discography.md"
        label: "Discography"
        name: "discography"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: 'Shantymen Albums'
            name: 'shantymen-albums'
            widget: 'list'
            fields:
              - { label: 'Album Name', name: 'album-name', widget: 'string' }
              - { label: 'Album Year', name: 'album-year', widget: 'string' }
              - { label: 'Album Artwork', name: 'album-artwork', widget: 'image' }
              - { label: 'Album Details & Track Listing', name: "album-details-track-listing", widget: 'markdown' }